#!/usr/bin/cloud-init
#cloud-config
runcmd:
  - useradd -u 1111 -m hyperuser
  - mkdir -p /home/hyperuser/.ssh
  - chmod 700 /home/hyperuser/.ssh
  - touch /home/hyperuser/.ssh/authorized_keys
  - chmod 600 /home/hyperuser/.ssh/authorized_keys
  - echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHpNCMGLRlBb87F/Lq9B6hGDBQeBrAw0xOh31ZkdrK0ZiPHM4egELbjclNhlluDfBG02x880mJ7qQyyy82PNgqj5Bn2hIs46OomF1/Q6UwXTMNoYLIe5Ft3XqsyVjXVeZ2jh/SiF+KpiCLCtX8ZdguV3DFRtx1LMuVgh84EDC+jL1+flj4a0Is06UfT3STuJDqPcP6GDShw/O6rbSsHtuMkRQG18I7QCdBfTY0lCsIX8phy4K6jD3heIX6vtLQfm40nNDxTFS9FLK2Av9oC4Te8pd6tCeqTCp976I2ob4Kr27Cdj4++FUsranTlCvZJdiI8RUwKEcAPTfvalm8+sJV ssh-key-2022-03-26' >> /home/hyperuser/.ssh/authorized_keys
  - chown -R hyperuser:hyperuser /home/hyperuser/.ssh/.*
  - mkdir /home/hyperuser/hyperstor
  - chown -R hyperuser:hyperuser /home/hyperuser/hyperstor/.*
  - echo 'hyp.str.priv.hyperspire.net:/hyperstor    /home/hyperuser/hyperstor    nfs    user=hyperuser,defaults,auto,_netdev,nofail    0 0' >> /etc/fstab
  - touch /etc/sudoers.d/1111-hyperuser
  - echo '%hyperuser    ALL=(ALL)    NOPASSWD: ALL' >> /home/hyperuser/1111-hyperuser
  - echo 'Defaults:hyperuser !requiretty' >> /home/hyperuser/1111-hyperuser
  - echo 'Defaults:hyperuser !visiblepw' >> /home/hyperuser/1111-hyperuser
  - mv /home/hyperuser/1111-hyperuser /etc/sudoers.d/
  - chmod 0440 /etc/sudoers.d/1111-hyperuser
  - useradd -u 2222 -s /usr/bin/nologin -m finger
  - mkdir -p /home/finger/.ssh
  - chmod 700 /home/finger/.ssh
  - touch /home/finger/.ssh/authorized_keys
  - chmod 600 /home/finger/.ssh/authorized_keys
  - echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHpNCMGLRlBb87F/Lq9B6hGDBQeBrAw0xOh31ZkdrK0ZiPHM4egELbjclNhlluDfBG02x880mJ7qQyyy82PNgqj5Bn2hIs46OomF1/Q6UwXTMNoYLIe5Ft3XqsyVjXVeZ2jh/SiF+KpiCLCtX8ZdguV3DFRtx1LMuVgh84EDC+jL1+flj4a0Is06UfT3STuJDqPcP6GDShw/O6rbSsHtuMkRQG18I7QCdBfTY0lCsIX8phy4K6jD3heIX6vtLQfm40nNDxTFS9FLK2Av9oC4Te8pd6tCeqTCp976I2ob4Kr27Cdj4++FUsranTlCvZJdiI8RUwKEcAPTfvalm8+sJV ssh-key-2022-03-26' >> /home/finger/.ssh/authorized_keys
  - chown finger:finger /home/finger/.ssh/.*
